### ISSUE TITLE
Error when importing to Python 3

### ISSUE THREAD

**Issue by morganwb** [Plutoberth/python-launch-library#2]
I get the following error when I attempt to import launchlibrary in python 3. Any advice?

pi@raspberrypi:~ $ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
import launchlibrary as ll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/launchlibrary/__init__.py", line 15, in <module>
    from .api import Api
  File "/usr/local/lib/python3.5/dist-packages/launchlibrary/api.py", line 36
    return "?mode={}&".format(self.mode) + "&".join([f"{k}={v}" for k, v in data.items()])
                                                              ^
SyntaxError: invalid syntax

**Comment by Plutoberth** [comment]
Hey @morganwb . This issue is caused by the fact that I'm using an f-string in that line, which was only introduced in Python 3.6. In retrospect, I should've placed a greater emphasis on backwards compatibility. 

If you cannot upgrade your Python installation (which is recommended in any case), you can convert all f-strings to regular formats (should be trivial)  and submit a pull request.

**Comment by morganwb** [comment]
Very much appreciated! I updated to Python 3.8 and it worked perfectly.
